name: test

on:
    - push
    - pull_request
    - release

jobs:
    build:
        strategy:
            fail-fast: false
            max-parallel: 6
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
                node:
                    - 12
                    - 13
        runs-on: ${{matrix.os}}
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v1
                with:
                    node-version: ${{matrix.node}}
            -   name: install
                run: yarn
            -   name: build
                run: npm run build
            -   name: test
                run: npm run test
